### ISSUE TITLE
Implement ORM to use instead of raw SQL

### ISSUE THREAD

**Issue by nisnevich** [nisnevich/eco-discord-lazy-consensus-bot#1]
Implement ORM (such as SQLAlchemy) to abstract from SQL, which would be a more secure way to interact with the database.

**Comment by kwinz** [comment]
I have never seen a good ORM in my life. https://en.wikipedia.org/wiki/Object%E2%80%93relational_impedance_mismatch
Maybe on some server platforms you can work around the impedance mismatch quirks whith a lot of overhead and not notice it.
But I would favor using SQL directly, querying exactly what we need and in a performant way.

**Comment by nisnevich** [comment]
Fixed by https://github.com/nisnevich/eco-discord-lazy-consensus-bot/pull/3, cudos @kiks12 !
