### ISSUE TITLE
Accepting proposals in English only

### ISSUE THREAD

**Issue by Lecturer1** [nisnevich/eco-discord-lazy-consensus-bot#16]
I suggest that the bot be set up to allow comments on sentences in English only. Proposals written in different languages can be mistranslated and therefore misunderstood by participants who speak other languages. 
To be able to print words in other languages in a proposal, such as a proper name, you can set the bot to print a limit of 10% characters in other languages.

**Comment by nisnevich** [comment]
Perhaps worth checking for just ~40-50% of English, if someone wants to duplicate text in second language (pretty often our people duplicate in Russian).

**Comment by nisnevich** [comment]
Done. Also added checking if the proposal actually starts with English.

**Comment by Lecturer1** [comment]
> Сделанный. Также добавлена ​​проверка, действительно ли предложение начинается с английского.

Super!
